#!/bin/sh

info=$(cat << EOF
btcs sign-message wallet address [message]

use bitscriptc to sign a message with an address
EOF
)

if [ "$#" -lt 1 ]; then
    echo "error: insert wallet" >&2
    exit 1
fi
case "$1" in
    -h|--help)
        echo "$info"
        exit 0
    ;;
esac
wallet="$1"
shift 1
if ! $BTC_BIN listwallets | jq -r '.[]' | grep "^${wallet}$" >/dev/null; then
    echo "error: wallet $wallet does not exists or is not loaded" >&2
    exit 1
fi

"$BTCS_HOME/scripts/btcs-extended-key-path" "$wallet" private |
bitscriptc sign-extended-key "$@"
